--S  game server
--G  gate server
--C	 game client
OP_NAME = {}
TEST_CPP_SERIALIZE_PACKET				= 1  --serialize packet
OP_NAME[TEST_CPP_SERIALIZE_PACKET] = "TEST_CPP_SERIALIZE_PACKET"
TEST_CPP_SERIALIZE_STREAM				= 2  --serialize stream_mode
OP_NAME[TEST_CPP_SERIALIZE_STREAM] = "TEST_CPP_SERIALIZE_STREAM"
TEST_CPP_TO_LUA_PACKET				= 3  --serialize packet
OP_NAME[TEST_CPP_TO_LUA_PACKET] = "TEST_CPP_TO_LUA_PACKET"
TEST_CPP_TO_LUA_STREAM				= 4  --serialize stream_mode
OP_NAME[TEST_CPP_TO_LUA_STREAM] = "TEST_CPP_TO_LUA_STREAM"
TEST_END				= 5  --end
OP_NAME[TEST_END] = "TEST_END"
TEST_01_BEGIN				= 6  --begin
OP_NAME[TEST_01_BEGIN] = "TEST_01_BEGIN"
TEST_LUA_TO_CPP_PACKET				= 7  --serialize packet
OP_NAME[TEST_LUA_TO_CPP_PACKET] = "TEST_LUA_TO_CPP_PACKET"
TEST_LUA_TO_CPP_STREAM				= 8  --serialize stream_mode
OP_NAME[TEST_LUA_TO_CPP_STREAM] = "TEST_LUA_TO_CPP_STREAM"
TEST_01_END				= 9  --end
OP_NAME[TEST_01_END] = "TEST_01_END"
TEST_BEGIN				= 0  --begin
OP_NAME[TEST_BEGIN] = "TEST_BEGIN"
OP_COUNT				= 10
